"""Document schema used by the regulatory intelligence system.

This schema describes the final stored document record.

It is separate from graph/state.py because:
1. graph/state.py describes data moving between nodes.
2. this file describes data saved after processing is complete.
"""

from typing import Any, TypedDict


class RegulatoryDocument(TypedDict, total=False):
    """Canonical document record for Layer 0 outputs."""

    # Unique id generated by storage_node.
    document_id: str

    # Source normalized by intake_node.
    source: str

    # Original path or URL.
    file_path: str

    # Text produced by ocr_node.
    raw_text: str

    # Structured information produced by metadata_node.
    metadata: dict[str, Any]

    # Final saved status.
    status: str
